import { Geist, Geist_Mono, Inter, Roboto, Manrope } from "next/font/google";
import "./globals.css";

import { ReduxProvider } from "../redux/Providers";
import Footer from "@/components/Footer";
import { getCurrentUser } from "@/lib/auth/getCurrentUser";
import HeaderServer from "@/components/header/HeaderServer";

// import StripeProvider from "@/components/StripeProvider";

const manrope = Manrope({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // choose what you need
  variable: "--font-manrope",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout({ children }) {
  const user = await getCurrentUser();
  // console.log("ROOT LAYOUT USER:", user);
  return (
    <html lang="en" className="test">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${roboto.variable} ${manrope.variable} `}
      >
        <ReduxProvider>
          {/* <StripeProvider> */}

          <div className="page-wrapper">
            {/* <Header /> */}
            <HeaderServer user={user} />
            {/* {console.log("RENDERING ROOT LAYOUT*************")} */}
            {children}
            <Footer />
          </div>
          {/* </StripeProvider> */}
        </ReduxProvider>
      </body>
    </html>
  );
}
