import { Geist, Geist_Mono, Inter, Roboto, Manrope } from "next/font/google";
import "./globals.css";

import { ReduxProvider } from "../redux/Providers";
import Footer from "@/components/footer/Footer";
import { getCurrentUser } from "@/lib/auth/getCurrentUser";
import { Suspense } from "react";
import UserHydrator from "@/lib/auth/UserHydrator";
import Header from "@/components/header/header/Header";
import PopupLogin from "@/components/auth/login/PopupLogin";
import LoginPopupHost from "@/components/auth/login/LoginPopupHost";

// import StripeProvider from "@/components/StripeProvider";

const manrope = Manrope({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // choose what you need
  variable: "--font-manrope",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout({ children }) {
  // const user = await getCurrentUser();
  // const safeUser = user
  //   ? {
  //       ...user,
  //       _id: user._id.toString(),
  //       createdAt: user.createdAt?.toISOString(),
  //       updatedAt: user.updatedAt?.toISOString(),
  //     }
  //   : null;
  console.log("ROOT LAYOUT -------------------------:");
  return (
    <html lang="en" className="test">
      <ReduxProvider>
        <Suspense fallback={null}>
          <body
            className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${roboto.variable} ${manrope.variable} `}
          >
            <div className="page-wrapper">
              {/* <UserHydrator user={safeUser} /> */}
              <Header />
              {children}
              <Footer />
            </div>
            <div id="modal-root"></div>
            {/* ✅ GLOBAL MODAL HOST */}
            <LoginPopupHost />
          </body>
        </Suspense>
      </ReduxProvider>
    </html>
  );
}
