import { Geist, Geist_Mono, Inter, Roboto, Manrope } from "next/font/google";
import "./globals.css";

import { ReduxProvider } from "../redux/Providers";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
// import ToastContainer from "@/components-ui/ToastContainer";

import ToastManual from "@/components-ui/ToastManual";
import ToastSuper from "@/components-ui/ToastSuper";
import PopupLogin from "@/components/PopupLogin";

import { setUserLogin } from "@/redux/store";
import { apiFetch } from "@/utils/apiFetch";
import UserLoader from "@/components/UserLoader";

const manrope = Manrope({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // choose what you need
  variable: "--font-manrope",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  // const pathname = usePathname();
  // const [displayChildren, setDisplayChildren] = useState(children);
  // const [fade, setFade] = useState(true);
  // const dispatch = useDispatch();

  return (
    <html lang="en" className="test">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${roboto.variable} ${manrope.variable} `}
      >
        <ReduxProvider>
          {/* Client-only wrapper for Redux + user fetch */}
          {/* <UserLoader /> */}
          <div className="page-wrapper">
            <Header />
            {children}
            <Footer />
            {/* <ToastContainer /> */}
            <ToastManual />
            <ToastSuper />
            <PopupLogin />
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
